---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
        files: .*\.(yaml|yml)$

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args:
          ["--ignore-unknown", "--no-error-on-unmatched-pattern", "!chart/**"]

  # Lint: YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args:
          [
            "-d {extends: relaxed, rules: {line-length: disable}, ignore: chart}",
            "-s",
          ]
        files: \.(yaml|yml)$

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--disable", "MD013 MD033"]

  # Lint: Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_checkov
      #- id: terraform_docs

  ## terrascan
  #- repo: https://github.com/accurics/terrascan
  #  rev: v1.10.0
  #  hooks:
  #    - id: terraform-pre-commit
  #      args: ["-i terraform --non-recursive examples/docs/"]

  # Versioning: Commit Messages & Changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
